// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for FormFieldType.
const (
	LONGTEXT       FormFieldType = "LONG_TEXT"
	MULTIPLECHOICE FormFieldType = "MULTIPLE_CHOICE"
	NUMBER         FormFieldType = "NUMBER"
	RATING         FormFieldType = "RATING"
	SHORTTEXT      FormFieldType = "SHORT_TEXT"
	SINGLECHOICE   FormFieldType = "SINGLE_CHOICE"
)

// Valid indicates whether the value is a known member of the FormFieldType enum.
func (e FormFieldType) Valid() bool {
	switch e {
	case LONGTEXT:
		return true
	case MULTIPLECHOICE:
		return true
	case NUMBER:
		return true
	case RATING:
		return true
	case SHORTTEXT:
		return true
	case SINGLECHOICE:
		return true
	default:
		return false
	}
}

// Defines values for FormState.
const (
	CANCELED  FormState = "CANCELED"
	DRAFT     FormState = "DRAFT"
	PUBLISHED FormState = "PUBLISHED"
)

// Valid indicates whether the value is a known member of the FormState enum.
func (e FormState) Valid() bool {
	switch e {
	case CANCELED:
		return true
	case DRAFT:
		return true
	case PUBLISHED:
		return true
	default:
		return false
	}
}

// Defines values for HealthResponseStatus.
const (
	Ok HealthResponseStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthResponseStatus enum.
func (e HealthResponseStatus) Valid() bool {
	switch e {
	case Ok:
		return true
	default:
		return false
	}
}

// Choice defines model for Choice.
type Choice struct {
	Label string `json:"label"`
	Value string `json:"value"`
}

// CreateFormField defines model for CreateFormField.
type CreateFormField struct {
	Configuration map[string]interface{} `json:"configuration"`
	Description   *string                `json:"description,omitempty"`
	Label         string                 `json:"label"`
	Required      bool                   `json:"required"`
	Type          FormFieldType          `json:"type"`
}

// CreateFormRequest defines model for CreateFormRequest.
type CreateFormRequest struct {
	Description *string           `json:"description,omitempty"`
	Fields      []CreateFormField `json:"fields"`
	Slug        string            `json:"slug"`
	Title       string            `json:"title"`
}

// CreateSubmissionRequest defines model for CreateSubmissionRequest.
type CreateSubmissionRequest struct {
	Answers []SubmissionAnswer `json:"answers"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// FormFieldType defines model for FormFieldType.
type FormFieldType string

// FormState defines model for FormState.
type FormState string

// FormSummary defines model for FormSummary.
type FormSummary struct {
	CreatedAt   time.Time `json:"created_at"`
	Description *string   `json:"description,omitempty"`
	Id          int64     `json:"id"`
	Slug        string    `json:"slug"`
	State       FormState `json:"state"`
	Title       string    `json:"title"`
	UpdatedAt   time.Time `json:"updated_at"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Status HealthResponseStatus `json:"status"`
}

// HealthResponseStatus defines model for HealthResponse.Status.
type HealthResponseStatus string

// MultipleChoiceConfiguration defines model for MultipleChoiceConfiguration.
type MultipleChoiceConfiguration struct {
	Choices       []Choice `json:"choices"`
	MaxSelections *int     `json:"max_selections,omitempty"`
	MinSelections *int     `json:"min_selections,omitempty"`
}

// NumberConfiguration defines model for NumberConfiguration.
type NumberConfiguration struct {
	Max  *float32 `json:"max,omitempty"`
	Min  *float32 `json:"min,omitempty"`
	Step *float32 `json:"step,omitempty"`
}

// PublicForm defines model for PublicForm.
type PublicForm struct {
	Description *string           `json:"description,omitempty"`
	Fields      []PublicFormField `json:"fields"`
	Id          int64             `json:"id"`
	Slug        string            `json:"slug"`
	Title       string            `json:"title"`
}

// PublicFormField defines model for PublicFormField.
type PublicFormField struct {
	Configuration map[string]interface{} `json:"configuration"`
	Description   *string                `json:"description,omitempty"`
	Id            int64                  `json:"id"`
	Label         string                 `json:"label"`
	Required      bool                   `json:"required"`
	Type          FormFieldType          `json:"type"`
}

// RatingConfiguration defines model for RatingConfiguration.
type RatingConfiguration struct {
	Max int `json:"max"`
	Min int `json:"min"`
}

// RegisterUserRequest defines model for RegisterUserRequest.
type RegisterUserRequest struct {
	Email    openapi_types.Email `json:"email"`
	Name     string              `json:"name"`
	Password string              `json:"password"`
}

// SingleChoiceConfiguration defines model for SingleChoiceConfiguration.
type SingleChoiceConfiguration struct {
	Choices []Choice `json:"choices"`
}

// SubmissionAnswer defines model for SubmissionAnswer.
type SubmissionAnswer struct {
	FieldId int64       `json:"field_id"`
	Value   interface{} `json:"value"`
}

// SubmissionCreated defines model for SubmissionCreated.
type SubmissionCreated struct {
	CreatedAt time.Time `json:"created_at"`
	Id        int64     `json:"id"`
}

// TextConfiguration defines model for TextConfiguration.
type TextConfiguration struct {
	MaxLength *int `json:"max_length,omitempty"`
	MinLength *int `json:"min_length,omitempty"`
}

// User defines model for User.
type User struct {
	Email openapi_types.Email `json:"email"`
	Id    int64               `json:"id"`
	Name  string              `json:"name"`
}

// ListFormsParams defines parameters for ListForms.
type ListFormsParams struct {
	FalqonSession *string `form:"falqon_session,omitempty" json:"falqon_session,omitempty"`
}

// CreateFormParams defines parameters for CreateForm.
type CreateFormParams struct {
	FalqonSession *string `form:"falqon_session,omitempty" json:"falqon_session,omitempty"`
}

// PublishFormParams defines parameters for PublishForm.
type PublishFormParams struct {
	FalqonSession *string `form:"falqon_session,omitempty" json:"falqon_session,omitempty"`
}

// CompleteGoogleLoginParams defines parameters for CompleteGoogleLogin.
type CompleteGoogleLoginParams struct {
	Code        *string `form:"code,omitempty" json:"code,omitempty"`
	State       *string `form:"state,omitempty" json:"state,omitempty"`
	Error       *string `form:"error,omitempty" json:"error,omitempty"`
	FalqonOauth *string `form:"falqon_oauth,omitempty" json:"falqon_oauth,omitempty"`
}

// LogoutParams defines parameters for Logout.
type LogoutParams struct {
	FalqonSession *string `form:"falqon_session,omitempty" json:"falqon_session,omitempty"`
}

// GetAuthSessionParams defines parameters for GetAuthSession.
type GetAuthSessionParams struct {
	FalqonSession *string `form:"falqon_session,omitempty" json:"falqon_session,omitempty"`
}

// CreateFormJSONRequestBody defines body for CreateForm for application/json ContentType.
type CreateFormJSONRequestBody = CreateFormRequest

// RegisterUserJSONRequestBody defines body for RegisterUser for application/json ContentType.
type RegisterUserJSONRequestBody = RegisterUserRequest

// CreateSubmissionJSONRequestBody defines body for CreateSubmission for application/json ContentType.
type CreateSubmissionJSONRequestBody = CreateSubmissionRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// ListForms Lista os formularios do usuario autenticado
	// (GET /admin/forms)
	ListForms(w http.ResponseWriter, r *http.Request, params ListFormsParams)
	// CreateForm Cria um formulario dinamico como rascunho
	// (POST /admin/forms)
	CreateForm(w http.ResponseWriter, r *http.Request, params CreateFormParams)
	// PublishForm Publica um formulario em rascunho
	// (POST /admin/forms/{formId}/publish)
	PublishForm(w http.ResponseWriter, r *http.Request, formId int64, params PublishFormParams)
	// BeginGoogleLogin Inicia o login com Google
	// (GET /auth/google)
	BeginGoogleLogin(w http.ResponseWriter, r *http.Request)
	// CompleteGoogleLogin Finaliza o login com Google
	// (GET /auth/google/callback)
	CompleteGoogleLogin(w http.ResponseWriter, r *http.Request, params CompleteGoogleLoginParams)
	// Logout Encerra a sessao atual
	// (POST /auth/logout)
	Logout(w http.ResponseWriter, r *http.Request, params LogoutParams)
	// RegisterUser Cadastra um usuario com e-mail e inicia sua sessao
	// (POST /auth/register)
	RegisterUser(w http.ResponseWriter, r *http.Request)
	// GetAuthSession Retorna o usuario autenticado
	// (GET /auth/session)
	GetAuthSession(w http.ResponseWriter, r *http.Request, params GetAuthSessionParams)
	// GetPublicForm Busca um formulario publicado pelo slug
	// (GET /forms/{slug})
	GetPublicForm(w http.ResponseWriter, r *http.Request, slug string)
	// CreateSubmission Valida e salva respostas de um formulario publicado
	// (POST /forms/{slug}/submissions)
	CreateSubmission(w http.ResponseWriter, r *http.Request, slug string)
	// GetHealth Consulta a saude da API
	// (GET /health)
	GetHealth(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// ListForms Lista os formularios do usuario autenticado
// (GET /admin/forms)
func (_ Unimplemented) ListForms(w http.ResponseWriter, r *http.Request, params ListFormsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// CreateForm Cria um formulario dinamico como rascunho
// (POST /admin/forms)
func (_ Unimplemented) CreateForm(w http.ResponseWriter, r *http.Request, params CreateFormParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// PublishForm Publica um formulario em rascunho
// (POST /admin/forms/{formId}/publish)
func (_ Unimplemented) PublishForm(w http.ResponseWriter, r *http.Request, formId int64, params PublishFormParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// BeginGoogleLogin Inicia o login com Google
// (GET /auth/google)
func (_ Unimplemented) BeginGoogleLogin(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// CompleteGoogleLogin Finaliza o login com Google
// (GET /auth/google/callback)
func (_ Unimplemented) CompleteGoogleLogin(w http.ResponseWriter, r *http.Request, params CompleteGoogleLoginParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Logout Encerra a sessao atual
// (POST /auth/logout)
func (_ Unimplemented) Logout(w http.ResponseWriter, r *http.Request, params LogoutParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// RegisterUser Cadastra um usuario com e-mail e inicia sua sessao
// (POST /auth/register)
func (_ Unimplemented) RegisterUser(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetAuthSession Retorna o usuario autenticado
// (GET /auth/session)
func (_ Unimplemented) GetAuthSession(w http.ResponseWriter, r *http.Request, params GetAuthSessionParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetPublicForm Busca um formulario publicado pelo slug
// (GET /forms/{slug})
func (_ Unimplemented) GetPublicForm(w http.ResponseWriter, r *http.Request, slug string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// CreateSubmission Valida e salva respostas de um formulario publicado
// (POST /forms/{slug}/submissions)
func (_ Unimplemented) CreateSubmission(w http.ResponseWriter, r *http.Request, slug string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetHealth Consulta a saude da API
// (GET /health)
func (_ Unimplemented) GetHealth(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListForms operation middleware
func (siw *ServerInterfaceWrapper) ListForms(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListFormsParams

	{
		var cookie *http.Cookie

		if cookie, err = r.Cookie("falqon_session"); err == nil {
			var value string
			err = runtime.BindStyledParameterWithOptions("simple", "falqon_session", cookie.Value, &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationCookie, Explode: true, Required: false, Type: "string", Format: ""})
			if err != nil {
				siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "falqon_session", Err: err})
				return
			}
			params.FalqonSession = &value

		}
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListForms(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateForm operation middleware
func (siw *ServerInterfaceWrapper) CreateForm(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateFormParams

	{
		var cookie *http.Cookie

		if cookie, err = r.Cookie("falqon_session"); err == nil {
			var value string
			err = runtime.BindStyledParameterWithOptions("simple", "falqon_session", cookie.Value, &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationCookie, Explode: true, Required: false, Type: "string", Format: ""})
			if err != nil {
				siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "falqon_session", Err: err})
				return
			}
			params.FalqonSession = &value

		}
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateForm(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PublishForm operation middleware
func (siw *ServerInterfaceWrapper) PublishForm(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "formId" -------------
	var formId int64

	err = runtime.BindStyledParameterWithOptions("simple", "formId", chi.URLParam(r, "formId"), &formId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "formId", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params PublishFormParams

	{
		var cookie *http.Cookie

		if cookie, err = r.Cookie("falqon_session"); err == nil {
			var value string
			err = runtime.BindStyledParameterWithOptions("simple", "falqon_session", cookie.Value, &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationCookie, Explode: true, Required: false, Type: "string", Format: ""})
			if err != nil {
				siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "falqon_session", Err: err})
				return
			}
			params.FalqonSession = &value

		}
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PublishForm(w, r, formId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// BeginGoogleLogin operation middleware
func (siw *ServerInterfaceWrapper) BeginGoogleLogin(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.BeginGoogleLogin(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CompleteGoogleLogin operation middleware
func (siw *ServerInterfaceWrapper) CompleteGoogleLogin(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params CompleteGoogleLoginParams

	// ------------- Optional query parameter "code" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "code", r.URL.Query(), &params.Code, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "code"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "code", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "state" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "state", r.URL.Query(), &params.State, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "state"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "state", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "error" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "error", r.URL.Query(), &params.Error, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "error"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "error", Err: err})
		}
		return
	}

	{
		var cookie *http.Cookie

		if cookie, err = r.Cookie("falqon_oauth"); err == nil {
			var value string
			err = runtime.BindStyledParameterWithOptions("simple", "falqon_oauth", cookie.Value, &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationCookie, Explode: true, Required: false, Type: "string", Format: ""})
			if err != nil {
				siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "falqon_oauth", Err: err})
				return
			}
			params.FalqonOauth = &value

		}
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CompleteGoogleLogin(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Logout operation middleware
func (siw *ServerInterfaceWrapper) Logout(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params LogoutParams

	{
		var cookie *http.Cookie

		if cookie, err = r.Cookie("falqon_session"); err == nil {
			var value string
			err = runtime.BindStyledParameterWithOptions("simple", "falqon_session", cookie.Value, &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationCookie, Explode: true, Required: false, Type: "string", Format: ""})
			if err != nil {
				siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "falqon_session", Err: err})
				return
			}
			params.FalqonSession = &value

		}
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Logout(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RegisterUser operation middleware
func (siw *ServerInterfaceWrapper) RegisterUser(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RegisterUser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAuthSession operation middleware
func (siw *ServerInterfaceWrapper) GetAuthSession(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetAuthSessionParams

	{
		var cookie *http.Cookie

		if cookie, err = r.Cookie("falqon_session"); err == nil {
			var value string
			err = runtime.BindStyledParameterWithOptions("simple", "falqon_session", cookie.Value, &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationCookie, Explode: true, Required: false, Type: "string", Format: ""})
			if err != nil {
				siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "falqon_session", Err: err})
				return
			}
			params.FalqonSession = &value

		}
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAuthSession(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPublicForm operation middleware
func (siw *ServerInterfaceWrapper) GetPublicForm(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "slug" -------------
	var slug string

	err = runtime.BindStyledParameterWithOptions("simple", "slug", chi.URLParam(r, "slug"), &slug, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "slug", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPublicForm(w, r, slug)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateSubmission operation middleware
func (siw *ServerInterfaceWrapper) CreateSubmission(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "slug" -------------
	var slug string

	err = runtime.BindStyledParameterWithOptions("simple", "slug", chi.URLParam(r, "slug"), &slug, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "slug", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateSubmission(w, r, slug)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/forms/{slug}", wrapper.GetPublicForm)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/forms/{slug}/submissions", wrapper.CreateSubmission)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/health", wrapper.GetHealth)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/auth/google", wrapper.BeginGoogleLogin)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/register", wrapper.RegisterUser)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/auth/google/callback", wrapper.CompleteGoogleLogin)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/auth/session", wrapper.GetAuthSession)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/logout", wrapper.Logout)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/admin/forms", wrapper.ListForms)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/admin/forms", wrapper.CreateForm)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/admin/forms/{formId}/publish", wrapper.PublishForm)
	})

	return r
}

type ListFormsRequestObject struct {
	Params ListFormsParams
}

type ListFormsResponseObject interface {
	VisitListFormsResponse(w http.ResponseWriter) error
}

type ListForms200JSONResponse []FormSummary

func (response ListForms200JSONResponse) VisitListFormsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListForms401JSONResponse ErrorResponse

func (response ListForms401JSONResponse) VisitListFormsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CreateFormRequestObject struct {
	Params CreateFormParams
	Body   *CreateFormJSONRequestBody
}

type CreateFormResponseObject interface {
	VisitCreateFormResponse(w http.ResponseWriter) error
}

type CreateForm201JSONResponse FormSummary

func (response CreateForm201JSONResponse) VisitCreateFormResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateForm401JSONResponse ErrorResponse

func (response CreateForm401JSONResponse) VisitCreateFormResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CreateForm409JSONResponse ErrorResponse

func (response CreateForm409JSONResponse) VisitCreateFormResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type CreateForm422JSONResponse ErrorResponse

func (response CreateForm422JSONResponse) VisitCreateFormResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type PublishFormRequestObject struct {
	FormId int64 `json:"formId"`
	Params PublishFormParams
}

type PublishFormResponseObject interface {
	VisitPublishFormResponse(w http.ResponseWriter) error
}

type PublishForm200JSONResponse FormSummary

func (response PublishForm200JSONResponse) VisitPublishFormResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type PublishForm401JSONResponse ErrorResponse

func (response PublishForm401JSONResponse) VisitPublishFormResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type PublishForm404JSONResponse ErrorResponse

func (response PublishForm404JSONResponse) VisitPublishFormResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type PublishForm409JSONResponse ErrorResponse

func (response PublishForm409JSONResponse) VisitPublishFormResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type BeginGoogleLoginRequestObject struct {
}

type BeginGoogleLoginResponseObject interface {
	VisitBeginGoogleLoginResponse(w http.ResponseWriter) error
}

type BeginGoogleLogin307ResponseHeaders struct {
	Location  string
	SetCookie string
}

type BeginGoogleLogin307Response struct {
	Headers BeginGoogleLogin307ResponseHeaders
}

func (response BeginGoogleLogin307Response) VisitBeginGoogleLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Location", fmt.Sprint(response.Headers.Location))
	w.Header().Set("Set-Cookie", fmt.Sprint(response.Headers.SetCookie))
	w.WriteHeader(307)
	return nil
}

type BeginGoogleLogin503JSONResponse ErrorResponse

func (response BeginGoogleLogin503JSONResponse) VisitBeginGoogleLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type CompleteGoogleLoginRequestObject struct {
	Params CompleteGoogleLoginParams
}

type CompleteGoogleLoginResponseObject interface {
	VisitCompleteGoogleLoginResponse(w http.ResponseWriter) error
}

type CompleteGoogleLogin302ResponseHeaders struct {
	Location  string
	SetCookie string
}

type CompleteGoogleLogin302Response struct {
	Headers CompleteGoogleLogin302ResponseHeaders
}

func (response CompleteGoogleLogin302Response) VisitCompleteGoogleLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Location", fmt.Sprint(response.Headers.Location))
	w.Header().Set("Set-Cookie", fmt.Sprint(response.Headers.SetCookie))
	w.WriteHeader(302)
	return nil
}

type CompleteGoogleLogin400JSONResponse ErrorResponse

func (response CompleteGoogleLogin400JSONResponse) VisitCompleteGoogleLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type LogoutRequestObject struct {
	Params LogoutParams
}

type LogoutResponseObject interface {
	VisitLogoutResponse(w http.ResponseWriter) error
}

type Logout204ResponseHeaders struct {
	SetCookie string
}

type Logout204Response struct {
	Headers Logout204ResponseHeaders
}

func (response Logout204Response) VisitLogoutResponse(w http.ResponseWriter) error {
	w.Header().Set("Set-Cookie", fmt.Sprint(response.Headers.SetCookie))
	w.WriteHeader(204)
	return nil
}

type RegisterUserRequestObject struct {
	Body *RegisterUserJSONRequestBody
}

type RegisterUserResponseObject interface {
	VisitRegisterUserResponse(w http.ResponseWriter) error
}

type RegisterUser201ResponseHeaders struct {
	SetCookie string
}

type RegisterUser201JSONResponse struct {
	Body    User
	Headers RegisterUser201ResponseHeaders
}

func (response RegisterUser201JSONResponse) VisitRegisterUserResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("Set-Cookie", fmt.Sprint(response.Headers.SetCookie))
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type RegisterUser409JSONResponse ErrorResponse

func (response RegisterUser409JSONResponse) VisitRegisterUserResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type RegisterUser422JSONResponse ErrorResponse

func (response RegisterUser422JSONResponse) VisitRegisterUserResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type GetAuthSessionRequestObject struct {
	Params GetAuthSessionParams
}

type GetAuthSessionResponseObject interface {
	VisitGetAuthSessionResponse(w http.ResponseWriter) error
}

type GetAuthSession200JSONResponse User

func (response GetAuthSession200JSONResponse) VisitGetAuthSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetAuthSession401JSONResponse ErrorResponse

func (response GetAuthSession401JSONResponse) VisitGetAuthSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetPublicFormRequestObject struct {
	Slug string `json:"slug"`
}

type GetPublicFormResponseObject interface {
	VisitGetPublicFormResponse(w http.ResponseWriter) error
}

type GetPublicForm200JSONResponse PublicForm

func (response GetPublicForm200JSONResponse) VisitGetPublicFormResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetPublicForm404JSONResponse ErrorResponse

func (response GetPublicForm404JSONResponse) VisitGetPublicFormResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type CreateSubmissionRequestObject struct {
	Slug string `json:"slug"`
	Body *CreateSubmissionJSONRequestBody
}

type CreateSubmissionResponseObject interface {
	VisitCreateSubmissionResponse(w http.ResponseWriter) error
}

type CreateSubmission201JSONResponse SubmissionCreated

func (response CreateSubmission201JSONResponse) VisitCreateSubmissionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateSubmission404JSONResponse ErrorResponse

func (response CreateSubmission404JSONResponse) VisitCreateSubmissionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type CreateSubmission422JSONResponse ErrorResponse

func (response CreateSubmission422JSONResponse) VisitCreateSubmissionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type GetHealthRequestObject struct {
}

type GetHealthResponseObject interface {
	VisitGetHealthResponse(w http.ResponseWriter) error
}

type GetHealth200JSONResponse HealthResponse

func (response GetHealth200JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetHealth503JSONResponse ErrorResponse

func (response GetHealth503JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// ListForms Lista os formularios do usuario autenticado
	// (GET /admin/forms)
	ListForms(ctx context.Context, request ListFormsRequestObject) (ListFormsResponseObject, error)
	// CreateForm Cria um formulario dinamico como rascunho
	// (POST /admin/forms)
	CreateForm(ctx context.Context, request CreateFormRequestObject) (CreateFormResponseObject, error)
	// PublishForm Publica um formulario em rascunho
	// (POST /admin/forms/{formId}/publish)
	PublishForm(ctx context.Context, request PublishFormRequestObject) (PublishFormResponseObject, error)
	// BeginGoogleLogin Inicia o login com Google
	// (GET /auth/google)
	BeginGoogleLogin(ctx context.Context, request BeginGoogleLoginRequestObject) (BeginGoogleLoginResponseObject, error)
	// CompleteGoogleLogin Finaliza o login com Google
	// (GET /auth/google/callback)
	CompleteGoogleLogin(ctx context.Context, request CompleteGoogleLoginRequestObject) (CompleteGoogleLoginResponseObject, error)
	// Logout Encerra a sessao atual
	// (POST /auth/logout)
	Logout(ctx context.Context, request LogoutRequestObject) (LogoutResponseObject, error)
	// RegisterUser Cadastra um usuario com e-mail e inicia sua sessao
	// (POST /auth/register)
	RegisterUser(ctx context.Context, request RegisterUserRequestObject) (RegisterUserResponseObject, error)
	// GetAuthSession Retorna o usuario autenticado
	// (GET /auth/session)
	GetAuthSession(ctx context.Context, request GetAuthSessionRequestObject) (GetAuthSessionResponseObject, error)
	// GetPublicForm Busca um formulario publicado pelo slug
	// (GET /forms/{slug})
	GetPublicForm(ctx context.Context, request GetPublicFormRequestObject) (GetPublicFormResponseObject, error)
	// CreateSubmission Valida e salva respostas de um formulario publicado
	// (POST /forms/{slug}/submissions)
	CreateSubmission(ctx context.Context, request CreateSubmissionRequestObject) (CreateSubmissionResponseObject, error)
	// GetHealth Consulta a saude da API
	// (GET /health)
	GetHealth(ctx context.Context, request GetHealthRequestObject) (GetHealthResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ListForms operation middleware
func (sh *strictHandler) ListForms(w http.ResponseWriter, r *http.Request, params ListFormsParams) {
	var request ListFormsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListForms(ctx, request.(ListFormsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListForms")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListFormsResponseObject); ok {
		if err := validResponse.VisitListFormsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateForm operation middleware
func (sh *strictHandler) CreateForm(w http.ResponseWriter, r *http.Request, params CreateFormParams) {
	var request CreateFormRequestObject

	request.Params = params

	var body CreateFormJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateForm(ctx, request.(CreateFormRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateForm")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateFormResponseObject); ok {
		if err := validResponse.VisitCreateFormResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PublishForm operation middleware
func (sh *strictHandler) PublishForm(w http.ResponseWriter, r *http.Request, formId int64, params PublishFormParams) {
	var request PublishFormRequestObject

	request.FormId = formId
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PublishForm(ctx, request.(PublishFormRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PublishForm")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PublishFormResponseObject); ok {
		if err := validResponse.VisitPublishFormResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// BeginGoogleLogin operation middleware
func (sh *strictHandler) BeginGoogleLogin(w http.ResponseWriter, r *http.Request) {
	var request BeginGoogleLoginRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.BeginGoogleLogin(ctx, request.(BeginGoogleLoginRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "BeginGoogleLogin")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(BeginGoogleLoginResponseObject); ok {
		if err := validResponse.VisitBeginGoogleLoginResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CompleteGoogleLogin operation middleware
func (sh *strictHandler) CompleteGoogleLogin(w http.ResponseWriter, r *http.Request, params CompleteGoogleLoginParams) {
	var request CompleteGoogleLoginRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CompleteGoogleLogin(ctx, request.(CompleteGoogleLoginRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CompleteGoogleLogin")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CompleteGoogleLoginResponseObject); ok {
		if err := validResponse.VisitCompleteGoogleLoginResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Logout operation middleware
func (sh *strictHandler) Logout(w http.ResponseWriter, r *http.Request, params LogoutParams) {
	var request LogoutRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Logout(ctx, request.(LogoutRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Logout")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(LogoutResponseObject); ok {
		if err := validResponse.VisitLogoutResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RegisterUser operation middleware
func (sh *strictHandler) RegisterUser(w http.ResponseWriter, r *http.Request) {
	var request RegisterUserRequestObject

	var body RegisterUserJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RegisterUser(ctx, request.(RegisterUserRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RegisterUser")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RegisterUserResponseObject); ok {
		if err := validResponse.VisitRegisterUserResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetAuthSession operation middleware
func (sh *strictHandler) GetAuthSession(w http.ResponseWriter, r *http.Request, params GetAuthSessionParams) {
	var request GetAuthSessionRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetAuthSession(ctx, request.(GetAuthSessionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAuthSession")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetAuthSessionResponseObject); ok {
		if err := validResponse.VisitGetAuthSessionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetPublicForm operation middleware
func (sh *strictHandler) GetPublicForm(w http.ResponseWriter, r *http.Request, slug string) {
	var request GetPublicFormRequestObject

	request.Slug = slug

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetPublicForm(ctx, request.(GetPublicFormRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetPublicForm")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetPublicFormResponseObject); ok {
		if err := validResponse.VisitGetPublicFormResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateSubmission operation middleware
func (sh *strictHandler) CreateSubmission(w http.ResponseWriter, r *http.Request, slug string) {
	var request CreateSubmissionRequestObject

	request.Slug = slug

	var body CreateSubmissionJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateSubmission(ctx, request.(CreateSubmissionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateSubmission")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateSubmissionResponseObject); ok {
		if err := validResponse.VisitCreateSubmissionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetHealth operation middleware
func (sh *strictHandler) GetHealth(w http.ResponseWriter, r *http.Request) {
	var request GetHealthRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealth(ctx, request.(GetHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealth")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHealthResponseObject); ok {
		if err := validResponse.VisitGetHealthResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"1FpZUyM5Ev4rCu087GHabsPM9PhlA9yGdqybJjBsbEQHS4iqxFZ3lVStg4Eh/N83UqrLZfni8LBPmLKU",
	"yuPLLzNVfqSRTDMpQBhNe49UR1NImfvYn0oeAX5iccwNl4IlZ0pmoAwHTXu3LNHQolnt0SNN2A0k+CHl",
	"YgRiYqa0975FzUMGtEe1UVxM6KxF71hiYe26WYsq+GG5gpj2vuabWvkhV+VyefMNIoNi+wqYgWOp0mMO",
	"Sbyl8pEUt3xiFcP1y/caZSFwdgw6Ujwr9qbsvjSs0+kEfFD5qlra/fnn1jrfVS55LL68kTIBJvBb/+SR",
	"/qTglvboX9pVgNt5dNulgy5wcdPNTkKhXu2rVsNBqwNwDj8saLNlCJY7sRt24i2a4bZyA6leZ3kTIDPn",
	"7aHfWjmbKcUe8Eud2MmaEHVbNGPGgBK0R//7le390dn77eoff/1nb6/8529//4kGlDfcJLBe/Oqs8EJy",
	"VUuHLA/O2N6kXGsuxdNCxIT+HdTmLq/OO3Q7K5AWbm4YVBwQMmGglFTnoDMpNGyd3jHUcqYKQwpas0no",
	"u4ZmTkK1PqTgfGr1HikIm+Le8acv5xfXF4P/XNAWHX05PSk+n15+Phqc0xYdD09PRoPr/qcvw/6Atujn",
	"y9HF8Kz+5PzwYnh6Uju3sgHPHRtm5s78eH54jEecXR6NhuNPg4+0RfuHp/3BaPBxuRSbpkw9bOtch634",
	"mjk43UqV4icaMwN7hqcQgn8j2Re+5/GcLC7MLweVHC4MTDyciixdkKALj6xjQ++6ekouyLJZvKWFDfRw",
	"pNBGtnoFW3X3zZ0UgtgnYImZPjEJ8ECr6yCR3wNQaKie7wpp89kmhmcJ+Hahv1kJDUPISdiCy32DMkfh",
	"3UUKT9n9tYYEIlRD5z0HT9H49yEwpVwsW99ZXN9kiNyGkKdObXoD6jkeStl9DZrCyctVDj7XBjIX6vso",
	"sZrfwefCEt/DBAwrNs8CBpzZm4RHmC7Pq+rPLeKVHmURbwb9+dSxjAg2SOoVJbip+p/YoD6dbsvGdeet",
	"qff2M/rTc2a4mLxADqbsPueQTi2PuksIZR3rNMzEHY64wjbAhGsD6lKDeloLBynjyVyw/ZNWvRHd74b6",
	"bcHSZsf6/pfOmo4VO2Stf5cqbmz9tTu388O6OuROb5XallJDbhpzMXmzZWmLsrHQP2+nviOj641zuxjM",
	"mxqWYoolq1X1o0a8gyZyQ8tCRFI7LmTNBdybZzLFdZIje5OmI7A23HAsaIpM8GIU8PS6UHDDBhVzLpEX",
	"nY+FGSKruHkYY1oV5U9+53BovZOQVfNHhcAevWXJD4n9m0NhpSXL+L8A8w7tEbdyoSuhh2dDkjHFSKQ4",
	"Uy2SuUrNFAGiXKsdgyLoBJswxaUmMRcs5ZHU78oOoEeP3fkEqxg5sjzBTYdnQ8waUNqf1Hn3/l0H/SUz",
	"ECzjtEf333Xe7TtCM1NnapvFKRdtPM/9PwGXEhhBB8VhTHt0xLU5ditwp2IpGDeYf93UOZ6yQiG7wpj5",
	"AcOd3+108gbEgPDlJsvQP6hM+5v2yVHJ24gp69Pm4qVAs2Nxw2npfEmstvgZdx503m+l3Sql5m8YAmqM",
	"cfqXhFkNwgCRlsB9xhWL2RxuXRjqiP16hV7VxXTtoseI1POgKu0izKIxPGKxRICxCUaW+nhfYUmVOoCJ",
	"6oLrlUDh+o0jGT+8mMcX7wxn85yB/exsAZAvF/I5HK7CneOG+G1BDlX5bYeqJHZCvjFiDU/4H4Uzut3d",
	"afARbrngEZOYLFXuEC7uWMK3zcK+4ozYtC6oIHYSyVQSxXRkxTSUg7PWHE+3H/HPMJ61Xe3QrkqFs/TM",
	"L1iRplgJaknqBNNmUtSTdYMO6M8vCy+ThXlpfoOJeLA7VWr+EEwSEHisKp2yQ0oYaMNiSZixLHG6ZKBS",
	"bqCIU8TkdjnpL0maaQnp2ly0ZtqeSDnxFzfBnukIJlycuDUjOXFz9hyi9zu/LvaG5xBzBRF21r5HlMSL",
	"oC06BRbnr0NGMirnhA0S1SoevDMeg9nr+xxdKai5E/f+3NnfXeAPiw4Fydg7xMW/vIYpyLiM7FDwiKP7",
	"EvQ9EmzlyCKiiAkv1t/iNEPbjliS3LDo+9IY92WaJWBgPswhlv1hQT1UTJi/31nu4lZ4X3GLv/VGQBdv",
	"tHEJaUt0zFaUvd/prgZ4DOROJqZE+q1yYIrfHNYPXrD4rMV6Pwdd0WbIBrKPuWDYED0V24mcSGuWdwwj",
	"//0OBr2DRXjkZQ9EBMpl9RwUnh7DbYrCwB9OGNF5EcZ6s5FvVX5huty79StV+jpTTujWdsdzjrMugO3L",
	"fOKMWMy06yEINMbPFwn3rvuSvZTxBIeVyrDdTyssxrEeCh3KOUXqBoP0cyWx7SnuAJBEwJsBhPviqW2R",
	"AhuBvyCBZcXyBAxuHpdc8cZukp4C6LJNLyDM/m9vic7BSCWwrKy+FwoCIB9LdWIns1UAqL3Y3WQazV9z",
	"bp76r4mBmu6bTI3y7QxqCAo3LlXj7BwhHFm9MASVa0kGiSR5JELDUD32bV2+mNHLi2Dz52GviIXXukRc",
	"/G3bjkvs4huwACIcWrRhmmiW3DH9piG543pZ+aa4z2vWyX+7pwS88/zLGbchhmXJsiRFpu6HVKuI0f/U",
	"ir4ifTV+zBWass+GBMgNE5FEE2PfUHDcwO+AO/Tsduw/GxIuSg0SBI2GlLAItJaESa9ss72RQlscKxnR",
	"zDpD8jdjRWjGD9pAirFxBVLdFbTTOD694a6mJjJyA4BVCe3RqTFZr912D6dSm96HzocORbrJ5T+Gr61c",
	"zN3km1Qq5eSWa4RD+IqbDygnkjjlgmMPZ/gdq8Q0avOiuBNQICLOUhCmIcbFvPaGqJLqkTy7mv0vAAD/",
	"/w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
